name: nextflow_nextstrain
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohttp=3.7.4=py39h3811e60_0
  - alsa-lib=1.2.3=h516909a_0
  - amply=0.1.4=py_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - atk-1.0=2.36.0=h3371d22_4
  - attmap=0.13.0=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - augur=11.1.2=py_0
  - auspice=2.23.0=h1b792b2_1
  - awscli=1.19.92=py39hf3d152e_0
  - azure-common=1.1.27=pyhd8ed1ab_0
  - azure-core=1.14.0=pyhd8ed1ab_0
  - azure-storage-blob=12.8.1=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bcbio-gff=0.6.6=pyh864c0ab_1
  - bcrypt=3.2.0=py39h3811e60_1
  - biopython=1.79=py39h3811e60_0
  - blinker=1.4=py_1
  - boto=2.49.0=py_0
  - boto3=1.17.92=pyhd8ed1ab_0
  - botocore=1.20.92=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39h3811e60_1001
  - bx-python=0.8.11=py39h5d76eff_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2021.5.30=ha878542_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py39hf3d152e_0
  - cffi=1.14.5=py39he32792d_0
  - chardet=4.0.0=py39hf3d152e_1
  - coincbc=2.10.5=hcee13e7_1
  - colorama=0.4.3=py_0
  - configargparse=1.4.1=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - coreutils=8.31=h516909a_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - curl=7.77.0=hea6ffbf_0
  - cvxopt=1.2.6=py39heb1511d_0
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py39h3811e60_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - docutils=0.15.2=py39hf3d152e_2
  - dropbox=11.10.0=pyhd8ed1ab_0
  - dsdp=5.8=hd9d9efa_1203
  - expat=2.4.1=h9c3ff4c_0
  - fasttree=2.1.10=h779adbc_5
  - fftw=3.3.9=nompi_h74d3f13_101
  - filechunkio=1.8=py_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2021.6.0=pyhd8ed1ab_0
  - ftputil=5.0.1=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.19.8.1=h0b5b191_1005
  - ghostscript=9.54.0=h9c3ff4c_1
  - giflib=5.2.1=h36c2ea0_2
  - git=2.30.2=pl5320h24fefe6_1
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.17=pyhd8ed1ab_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - google-api-core=1.26.3=pyhd8ed1ab_0
  - google-api-python-client=2.8.0=pyhd8ed1ab_0
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-httplib2=0.1.0=pyhd8ed1ab_0
  - google-cloud-core=1.5.0=pyhd3deb0d_0
  - google-cloud-storage=1.38.0=pyh44b312d_0
  - google-crc32c=1.1.2=py39hb81f231_0
  - google-resumable-media=1.2.0=pyhd3deb0d_0
  - googleapis-common-protos=1.53.0=py39hf3d152e_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.47.2=h85b4f2f_0
  - grpcio=1.38.0=py39hff7568b_0
  - gsl=2.6=he838d99_2
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - harfbuzz=2.8.1=h83ec7ef_0
  - httplib2=0.19.1=pyhd8ed1ab_0
  - icu=68.1=h58526e2_0
  - idna=2.10=pyh9f0ad1d_0
  - imagemagick=7.0.11_14=pl5320hb118871_0
  - importlib-metadata=4.5.0=py39hf3d152e_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipython_genutils=0.2.0=py_1
  - iqtree=2.1.2=h56fc30b_0
  - isodate=0.6.0=py_1
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_core=4.7.1=py39hf3d152e_0
  - kiwisolver=1.3.1=py39h1a9c180_1
  - krb5=1.19.1=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcrc32c=1.1.1=h9c3ff4c_2
  - libcurl=7.77.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgd=2.3.2=h78a0170_0
  - libgfortran-ng=9.3.0=hff62375_19
  - libgfortran5=9.3.0=hff62375_19
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=9_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.15=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.17.2=h780b84a_0
  - librsvg=2.50.7=hc3c00ef_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=h6de172a_19
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h58526e2_1007
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.41.0=h7f98852_0
  - libwebp=1.2.0=h3452ae3_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h72842e0_0
  - logmuse=0.2.6=pyh8c360ce_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - lzo=2.10=h516909a_1000
  - mafft=7.480=h779adbc_0
  - markupsafe=2.0.1=py39h3811e60_0
  - matplotlib-base=3.4.2=py39h2fa2bec_0
  - metis=5.1.0=h58526e2_1006
  - more-itertools=8.8.0=pyhd8ed1ab_0
  - msrest=0.6.21=pyh44b312d_0
  - multidict=5.1.0=py39h3811e60_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - netifaces=0.10.9=py39h3811e60_1003
  - networkx=2.5=py_0
  - nextalign=0.2.0=h9ee0642_1
  - nextflow=21.04.0=h4a94de4_0
  - nextstrain=20200304=hdfd78af_1
  - nextstrain-cli=3.0.3=py_0
  - nodejs=15.14.0=h92b4a50_0
  - numpy=1.20.3=py39hdbf815f_1
  - oauth2client=4.1.3=py_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=11.0.9.1=h5cc2fde_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.4=py39hde0f152_0
  - pango=1.48.5=hb8ff022_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - peppy=0.31.1=pyhd8ed1ab_0
  - perl=5.32.1=0_h7f98852_perl5
  - pillow=8.2.0=py39hf95b381_1
  - pip=21.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - pluggy=0.13.1=py39hf3d152e_4
  - ply=3.11=py_1
  - prettytable=2.1.0=pyhd8ed1ab_0
  - protobuf=3.17.2=py39he80948d_0
  - psutil=5.8.0=py39h3811e60_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulp=2.4=py39hf3d152e_0
  - py=1.10.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pygraphviz=1.7=py39h78163bd_0
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pynacl=1.4.0=py39h3811e60_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39h3811e60_2
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py39hf3d152e_3
  - pytest=6.2.4=py39hf3d152e_0
  - python=3.9.4=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=1.0.0=pyhd8ed1ab_0
  - python-lzo=1.12=py39h265373d_1003
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - ratelimiter=1.2.0=py_1002
  - raxml=8.2.12=h779adbc_3
  - readline=8.1=h46c0cb4_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - s3fs=0.4.2=py_0
  - s3transfer=0.4.2=pyhd8ed1ab_0
  - scipy=1.6.3=py39hee8e79c_0
  - setuptools=49.6.0=py39hf3d152e_3
  - simplejson=3.17.2=py39h3811e60_2
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=5.1.0=pyhd8ed1ab_0
  - smmap=3.0.5=pyh44b312d_0
  - snakemake=6.4.1=hdfd78af_0
  - snakemake-minimal=6.4.1=pyhdfd78af_0
  - sqlite=3.35.5=h74cdb3f_0
  - stone=3.2.1=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - suitesparse=5.7.2=h7a0d4b7_0
  - tbb=2020.2=h4bd325d_4
  - tk=8.6.10=h21135ba_1
  - toml=0.10.2=pyhd8ed1ab_0
  - toposort=1.6=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_1
  - traitlets=5.0.5=py_0
  - treetime=0.8.1=pyh3252c3a_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2021a=he74cb21_0
  - ubiquerg=0.6.1=pyh9f0ad1d_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.5=pyhd8ed1ab_0
  - vcftools=0.1.16=h9a82719_5
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.36.2=pyhd3deb0d_0
  - wrapt=1.12.1=py39h3811e60_3
  - xmlrunner=1.7.7=py_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.5.1=py39h07f9747_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
